### ISSUE TITLE
hex2bin(): Hexadecimal input string must have an even length

### ISSUE THREAD

**Issue by amenk** [mpchadwick/straceout-utils#9]
PHP Warning:  hex2bin(): Hexadecimal input string must have an even length in /home/amk/local-workspace/straceout-utils/src/StraceOutUtils/Processor/MysqlQueryResult.php on line 61
	sendto(11, "\x09\x02\x00\x00\x03\x53\x45\x4c\x45\x43\x54\x20\x60\x63\x61\x74\x61\x6c\x6f\x67\x5f\x70\x72\x6f\x64\x75\x63\x74\x5f\x65\x6e\x74"..., 525, MSG_DONTWAIT, NULL, 0) = 525
	poll([{fd=11, events=POLLIN|POLLERR|POLLHUP}], 1, 86400000) = 1 ([{fd=11, revents=POLLIN}])
	recvfrom(11, "\x01\x00\x00\x01\x07\x74\x00\x00\x02\x03\x64\x65\x66\x0c\x6b\x75\x65\x62\x6c\x65\x72\x5f\x70\x72\x6f\x64\x21\x63\x61\x74\x61\x6c"..., 3129, MSG_DONTWAIT, NULL, NULL) = 888
	PHP Warning:  hex2bin(): Hexadecimal input string must have an even length in /home/amk/local-workspace/straceout-utils/src/StraceOutUtils/Processor/MysqlQueryResult/PacketParser.php on line 192
	-- Begin -- StraceOutUtils\Processor\MysqlQueryResult

**Comment by amenk** [comment]
We should have a sample strace command line in the documentation.

This works a bit better

    strace -s 65535 -x -p 23227 -o /tmp/strace-cron-out.txt

So strings are not cutted away.

**Comment by mpchadwick** [comment]
Yeah, I think this is covered under this issue?

https://github.com/mpchadwick/straceout-utils/issues/8

I'm planning to add detection to the processing of `recvfrom` buffers to see if they've been truncated. Providing an example using `-s` in the README is probably a good idea too.

**Comment by mpchadwick** [comment]
Clarified this in https://github.com/mpchadwick/straceout-utils/commit/33864133fbae2384fb01f581c47c47882648024f
